[package]
name = "neco"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["MiyakoMeow"]

[dependencies]


[profile.release]
lto = "thin"

[lints.rust]
missing_docs = "deny"
dead_code = "deny"
unused_crate_dependencies = "deny"
unused_extern_crates = "deny"
unused_imports = "deny"
unused_variables = "deny"
unused_assignments = "deny"
unused_mut = "deny"
unused_braces = "deny"
unused_must_use = "deny"
unused_unsafe = "deny"
unused_attributes = "deny"
unused_macros = "deny"
unused_allocation = "deny"
unused_labels = "deny"

[lints.rustdoc]
broken_intra_doc_links = "deny"
private_doc_tests = "deny"
invalid_html_tags = "deny"
bare_urls = "deny"

[lints.clippy]
pedantic = "deny"

missing_docs_in_private_items = "deny"

missing_errors_doc = "deny"
must_use_candidate = "deny"
mod_module_files = "deny"

indexing_slicing = "deny"
panic = "deny"
unwrap_used = "deny"
expect_used = "deny"
todo = "deny"
unimplemented = "deny"
unreachable = "deny"
panic_in_result_fn = "deny"

print_stderr = "deny"
print_stdout = "deny"

# Assert-related lints
assertions_on_constants = "deny"
assertions_on_result_states = "deny"
bool_assert_comparison = "deny"
